GET http://localhost:5059/genres
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYWIxMmE0ZC0zM2VmLTRiNzAtYWJhOS1jMGIyMmUwYzE3ZjEiLCJlbWFpbCI6ImVtYWlsMkBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJlbWFpbDJAZXhhbXBsZS5jb20iLCJqdGkiOiI1YjExYmVjOS1jODcyLTRjNjItYWE4NS00OTU1ODllNGIwNDEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzUyNTc0ODM2fQ.ME-6OkfdTEnXVjw2bE0OZPziM1f9c3bagzaryrGUwpg  
