### Get all
GET http://localhost:5059/songs

### Get by Id
GET http://localhost:5059/songs/3

### Search by name
GET http://localhost:5059/songs/search?request=song
Authorization: Bearer 

### Search by genre
GET http://localhost:5059/songs/genre?genreid=2
Authorization: Bearer 

### Create song
POST http://localhost:5059/songs
Content-Type: application/json
Authorization: Bearer 
{
  "name": "newSong",
  "genreId": 4,
  "lenght": 169,
  "listens": 984
}

### Update song
PUT http://localhost:5059/songs/1
Content-Type: application/json
Authorization: Bearer 
{
  "name": "updatedSong",
  "genreId": 1,
  "lenght": 209,
  "listens": 2780
}

### Delete song
DELETE http://localhost:5059/songs/2
Authorization: Bearer 